// <auto-generated />
namespace BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KhoitaodulieuCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoitaodulieuCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202303040259562_Khoi tao du lieu Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
